'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Manage

    ''' <summary>
    ''' Contrôle SuccessMessagePlaceHolder.
    ''' </summary>
    ''' <remarks>
    ''' Champ généré automatiquement.
    ''' Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
    ''' </remarks>
    Protected WithEvents SuccessMessagePlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' Contrôle setPassword.
    ''' </summary>
    ''' <remarks>
    ''' Champ généré automatiquement.
    ''' Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
    ''' </remarks>
    Protected WithEvents setPassword As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' Contrôle password.
    ''' </summary>
    ''' <remarks>
    ''' Champ généré automatiquement.
    ''' Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
    ''' </remarks>
    Protected WithEvents password As Global.System.Web.UI.WebControls.TextBox

    ''' <summary>
    ''' Contrôle confirmPassword.
    ''' </summary>
    ''' <remarks>
    ''' Champ généré automatiquement.
    ''' Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
    ''' </remarks>
    Protected WithEvents confirmPassword As Global.System.Web.UI.WebControls.TextBox

    ''' <summary>
    ''' Contrôle changePasswordHolder.
    ''' </summary>
    ''' <remarks>
    ''' Champ généré automatiquement.
    ''' Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
    ''' </remarks>
    Protected WithEvents changePasswordHolder As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' Contrôle changePasswordUserName.
    ''' </summary>
    ''' <remarks>
    ''' Champ généré automatiquement.
    ''' Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
    ''' </remarks>
    Protected WithEvents changePasswordUserName As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' Contrôle CurrentPasswordLabel.
    ''' </summary>
    ''' <remarks>
    ''' Champ généré automatiquement.
    ''' Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
    ''' </remarks>
    Protected WithEvents CurrentPasswordLabel As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' Contrôle CurrentPassword.
    ''' </summary>
    ''' <remarks>
    ''' Champ généré automatiquement.
    ''' Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
    ''' </remarks>
    Protected WithEvents CurrentPassword As Global.System.Web.UI.WebControls.TextBox

    ''' <summary>
    ''' Contrôle NewPasswordLabel.
    ''' </summary>
    ''' <remarks>
    ''' Champ généré automatiquement.
    ''' Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
    ''' </remarks>
    Protected WithEvents NewPasswordLabel As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' Contrôle NewPassword.
    ''' </summary>
    ''' <remarks>
    ''' Champ généré automatiquement.
    ''' Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
    ''' </remarks>
    Protected WithEvents NewPassword As Global.System.Web.UI.WebControls.TextBox

    ''' <summary>
    ''' Contrôle ConfirmNewPasswordLabel.
    ''' </summary>
    ''' <remarks>
    ''' Champ généré automatiquement.
    ''' Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
    ''' </remarks>
    Protected WithEvents ConfirmNewPasswordLabel As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' Contrôle ConfirmNewPassword.
    ''' </summary>
    ''' <remarks>
    ''' Champ généré automatiquement.
    ''' Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
    ''' </remarks>
    Protected WithEvents ConfirmNewPassword As Global.System.Web.UI.WebControls.TextBox
    
End Class
